---
- hosts: all

  tasks:
    - name: Gather the package facts
      package_facts:
        manager: auto

#    - name: Print the package facts
#      debug:
#        var: ansible_facts.packages

    - name: Check whether a package called foobar is installed
      debug:
          msg: "{{ ansible_facts.packages['{{ app }}'] | length }} versions of foobar are installed!"
      when: "'{{ app }}' in ansible_facts.packages"
