---
- hosts: equipos-fedora
  become: True

  tasks:
    - name: download metricbeat rpm
      get_url:
        url: "https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.0-x86_64.rpm"
        dest: /tmp/metricbeat.rpm

    - name: Install package metricbeat.
      yum:
        name: /tmp/metricbeat.rpm
        state: present

    - name: Copy file with owner and permissions
      copy:
        src: archivos/metricbeat.yml
        dest: /etc/metricbeat/metricbeat.yml
        owner: root
        group: root
        mode: '0644'

    - name: Ejecutamos el comando para habilitar el modulo sistema.
      shell: metricbeat modules enable system

    - name: Configuramos el mismos
      shell: metricbeat setup

    - name: enable service httpd and ensure it is not masked
      systemd:
        name: metricbeat
        enabled: yes

    - name: Make sure a service is running
      systemd:
        state: started
        name: metricbeat
