---
- hosts: all

  tasks:
    - name: upgrade all packages on fedora
      yum: name=* state=latest
      when: ansible_distribution == "CentOS" or ansible_distribution == "Fedora"

    - name: upgrade all paquetes on ubuntu
      apt: name=* state=latest
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
