- name: Instalamos curl
  yum: name=curl state=latest

- name: Descargamos el paquete para fedora
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.9.3-x86_64.rpm
    dest: /tmp/metricbeat-7.9.3-x86_64.rpm
    mode: '0440'

- name: Instalamos el paquete en fedora
  yum:
    name: /tmp/metricbeat-7.9.3-x86_64.rpm

- name: borramos el paquete en fedora
  file:
    path: /tmp/metricbeat-7.9.3-x86_64.rpm
    state: absent
